<a href="https://colab.research.google.com/github/hubcborja/Trabajo_grado_ECIJG/blob/main/Comtrade_Free_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Codigo de API Comtrade

Recuperado de https://github.com/uncomtrade/comtradeapicall/blob/main/tests/example%20calling%20functions%20-%20notebook.ipynb

## Librerías y conexión

In [3]:
import sys
!{sys.executable} -m pip install --upgrade comtradeapicall

Collecting comtradeapicall
  Downloading comtradeapicall-1.3.0-py3-none-any.whl.metadata (21 kB)
Downloading comtradeapicall-1.3.0-py3-none-any.whl (20 kB)
Installing collected packages: comtradeapicall
Successfully installed comtradeapicall-1.3.0

In [114]:
import pandas as pd
import requests
import comtradeapicall
import time
import os
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format

In [5]:
import importlib.metadata
version = importlib.metadata.version("comtradeapicall")
print("comtradeapicall version:", version)

comtradeapicall version: 1.3.0

In [8]:
PrimaryKey='cde7e1ab17694a84a7554b02b5e8f489'
SecondaryKey='d46468208db74e9c8a3ec81fb5d876b2'

In [23]:
mydf = comtradeapicall.getFinalDataAvailability(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS',
                                                period='2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025', reporterCode='170')
mydf

,datasetCode,typeCode,freqCode,period,reporterCode,reporterISO,reporterDesc,classificationCode,classificationSearchCode,isOriginalClassification,isExtendedFlowCode,isExtendedPartnerCode,isExtendedPartner2Code,isExtendedCmdCode,isExtendedCustomsCode,isExtendedMotCode,totalRecords,datasetChecksum,firstReleased,lastReleased
0,20170200601072100,C,A,2006,170,COL,Colombia,H2,HS,True,True,True,False,True,False,False,144440,1467177480,2007-03-19T08:11:57.28,2011-04-16T13:09:38.7333333
1,20170200701082100,C,A,2007,170,COL,Colombia,H3,HS,True,False,True,False,True,False,False,145127,1275774234,2008-05-02T16:57:17.7166667,2011-04-16T13:54:40.7066667
2,20170200801082100,C,A,2008,170,COL,Colombia,H3,HS,True,False,True,False,True,False,False,144778,1521521383,2009-04-09T11:26:40.2833333,2011-04-16T14:41:57.73
3,20170200901082100,C,A,2009,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,147595,-583338098,2010-03-02T12:31:00.6966667,2011-04-16T15:15:26.3166667
4,20170201001082100,C,A,2010,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,149434,-1848505451,2011-03-03T14:32:08.0466667,2011-03-03T14:32:08.0466667
5,20170201101082100,C,A,2011,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,155867,377627254,2012-03-21T18:25:49.9666667,2012-03-21T18:25:49.9666667
6,20170201201092100,C,A,2012,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,156042,968658935,2013-09-07T14:23:33.2,2013-09-07T14:23:33.2
7,20170201301092100,C,A,2013,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,158505,-347970151,2014-04-04T18:31:41.8,2014-04-04T18:31:41.8
8,20170201401092100,C,A,2014,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,160368,1626408517,2015-07-23T14:29:48.01,2015-07-23T14:29:48.01
9,20170201501092100,C,A,2015,170,COL,Colombia,H4,HS,True,False,True,False,True,False,False,157146,983557154,2016-09-01T19:10:30.06,2016-09-01T19:10:30.06
10,20170201601092100,C,A,2016,170,COL,Colombia,H4,HS,True,False,True,False,True,False,False,158225,-1885371501,2017-05-05T19:09:35.3,2017-05-05T19:09:35.3
11,20170201701182100,C,A,2017,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1349644,-1377630067,2018-07-09T13:01:27.39,2018-07-09T13:01:27.39
12,20170201801182100,C,A,2018,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1367116,-1176784435,2019-04-22T08:03:27.4266667,2019-04-22T08:03:27.4266667
13,20170201901182100,C,A,2019,170,COL,Colombia,H5,HS,True,False,True,True,True,True,True,2884876,192638454,2020-06-29T16:09:46.98,2024-07-24T11:29:10.0833333
14,20170202001182100,C,A,2020,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1419256,683623520,2021-08-04T01:25:08.1066667,2026-03-26T02:44:54.24
15,20170202101182100,C,A,2021,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1484983,824612050,2022-06-02T20:26:52.2666667,2026-03-27T06:13:18.1433333
16,20170202201202100,C,A,2022,170,COL,Colombia,H6,HS,True,False,True,True,True,True,True,3090896,1171875941,2023-10-12T00:45:16.5933333,2026-02-16T08:07:05.61
17,20170202301202100,C,A,2023,170,COL,Colombia,H6,HS,True,False,True,True,True,True,True,3072312,-580089957,2024-06-11T18:43:13.9533333,2026-02-10T08:04:35.82
18,20170202401202100,C,A,2024,170,COL,Colombia,H6,HS,True,False,True,True,True,False,True,1550473,486048189,2025-10-01T16:40:42.3733333,2026-03-27T22:03:53.2533333

## Obtención datos para Colombia 2021 a 2024

In [46]:
imp21 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2021',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp22 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2022',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp23 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2023',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp24 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2024',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

exp21 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2021',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp22 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2022',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp23 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2023',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp24 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2024',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [47]:
#Conteo para las importaciones
print(imp21['partnerCode'].size)
print(imp22['partnerCode'].size)
print(imp23['partnerCode'].size)
print(imp24['partnerCode'].size)
# Conteo para las exportaciones
print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)

95155
99119
97152
97103
60447
60447
60447
60447

In [48]:
imports21_24=pd.concat([imp21, imp22, imp23, imp24])
exports21_24=pd.concat([exp21, exp22, exp23, exp24])

In [58]:
exports21_24

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,0,W00,World,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,160725206.52,160725206.52,0,False,True
1,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,32,ARG,Argentina,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,3015.00,3015.00,0,False,True
2,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,40,AUT,Austria,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,50.00,50.00,0,False,True
3,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,56,BEL,Belgium,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,200.00,200.00,0,False,True
4,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,68,BOL,Bolivia (Plurinational State of),0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,830.00,830.00,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65878,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,860,UZB,Uzbekistan,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,645909.10,645909.10,0,False,True
65879,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,862,VEN,Venezuela,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,True,0.00,False,None,1003583583.61,1003583583.61,4,False,True
65880,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,887,YEM,Yemen,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,292992.60,292992.60,0,False,True
65881,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,894,ZMB,Zambia,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,184012.60,184012.60,0,False,True
65882,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,899,_X,"Areas, nes",0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,True,0.00,False,None,18793159.87,18793159.87,4,False,True

In [75]:
print(imports21_24['partnerCode'].unique().size)
print(exports21_24['partnerCode'].unique().size)

219
199

In [83]:
print(imports21_24['partnerISO'].unique())
print(exports21_24['partnerISO'].unique())

['W00' 'ARG' 'AUS' 'AUT' 'BEL' 'BOL' 'BRA' 'CAN' 'CHL' 'CRI' 'CZE' 'DNK'
 'DOM' 'ECU' 'DEU' 'HUN' 'ITA' 'KOR' 'LTU' 'MEX' 'OMN' 'NLD' 'ABW' 'NGA'
 'PAN' 'PER' 'PRT' 'QAT' 'ROU' 'RUS' 'VNM' 'ESP' 'CHE' 'THA' 'UKR' 'GBR'
 'USA' 'URY' 'VEN' '_X ' 'PRY' 'SLB' 'MMR' 'CHN' 'GHA' 'GRL' 'GTM' 'ISL'
 'IDN' 'CIV' 'JPN' 'MDV' 'MRT' 'MUS' 'S19' 'NZL' 'NOR' 'PAK' 'PHL' 'POL'
 'SEN' 'SYC' 'IND' 'SUR' 'TTO' 'TUR' 'TZA' 'FRA' 'IRL' 'ISR' 'HND' 'KEN'
 'ZAF' 'HKG' 'MAR' 'EGY' 'DZA' 'BGR' 'GEO' 'GRC' 'IRN' 'LBN' 'SGP' 'ARE'
 'TUN' 'LKA' 'LBR' 'MDG' 'NPL' 'RWA' 'SYR' 'SLV' 'FIN' 'NIC' 'ALB' 'HRV'
 'MYS' 'NAM' 'SDN' 'UZB' 'HTI' 'BEN' 'SWE' 'X2 ' 'SRB' 'SVK' 'SAU' 'SVN'
 'JOR' 'EST' 'LVA' 'BRB' 'CUB' 'GUY' 'KHM' 'MOZ' 'BHR' 'BLR' 'CYP' 'JAM'
 'MDA' 'PCN' 'BGD' 'BIH' 'GAB' 'KAZ' 'KWT' 'LUX' 'ARM' 'BLZ' 'PRK' 'MAC'
 'MLT' 'SWZ' 'TKL' 'COM' 'LAO' 'CMR' 'PYF' 'CCK' 'SLE' 'ASM' 'ATG' 'AZE'
 'BTN' 'COG' 'ERI' 'GMB' 'CUW' 'NER' 'KNA' 'AIA' 'MKD' 'CYM' 'FRO' 'IRQ'
 'LBY' 'UGA' 'GRD' 'NRU' 'GIN' 'AND' 'COK' 'PLW' 'BRN' 'ETH' 'LSO' 'CPV'
 'TJK' 'TKM' 'DMA' 'GUM' 'BWA' 'VGB' 'AFG' 'ATF' 'PSE' 'KGZ' 'VAT' 'MNG'
 'NIU' 'SHN' 'SMR' 'STP' 'BHS' 'CAF' 'GIB' 'MWI' 'MLI' 'TON' 'TUV' 'WLF'
 'MSR' 'NFK' 'FSM' 'BDI' 'AGO' 'FJI' 'BFA' 'PNG' 'MNP' 'TGO' 'WSM' 'NCL'
 'ZWE' 'TCD' 'TLS' 'TCA' 'ZMB' 'BMU' 'CXR' 'IOT' 'MHL' 'VCT' 'BES' 'SOM'
 'LCA' 'DJI' 'KIR']
['W00' 'ARG' 'AUT' 'BEL' 'BOL' 'BRA' 'CAN' 'CHL' 'CRI' 'CYP' 'CZE' 'DNK'
 'DOM' 'ECU' 'SLV' 'EST' 'FRA' 'DEU' 'GTM' 'HND' 'HKG' 'HUN' 'IDN' 'IRQ'
 'IRL' 'ISR' 'ITA' 'JPN' 'JOR' 'KOR' 'LBN' 'MYS' 'MLT' 'MEX' 'NAM' 'NLD'
 'CUW' 'ABW' 'NOR' 'PAN' 'PRY' 'PER' 'PHL' 'PRT' 'ROU' 'RUS' 'SAU' 'IND'
 'VNM' 'ZAF' 'ESP' 'SWE' 'CHE' 'THA' 'ARE' 'EGY' 'GBR' 'USA' 'URY' 'VEN'
 'CHN' 'COG' 'GNQ' 'GAB' 'GEO' 'CIV' 'LBR' 'LBY' 'QAT' 'SLE' 'TUR' 'BGR'
 'FIN' 'S19' 'OMN' 'PAK' 'POL' 'SGP' 'AUS' 'GUY' 'SUR' 'TTO' '_X ' 'SVK'
 'X2 ' 'AFG' 'ATG' 'AZE' 'BHS' 'BHR' 'BIH' 'VGB' 'BLR' 'HRV' 'ETH' 'GHA'
 'GRD' 'GUM' 'JAM' 'KAZ' 'KEN' 'PRK' 'KWT' 'KGZ' 'LVA' 'LTU' 'MDA' 'MNE'
 'MAR' 'NZL' 'NIC' 'KNA' 'LCA' 'SVN' 'TJK' 'UKR' 'CUB' 'ALB' 'DZA' 'KHM'
 'GRC' 'TUN' 'BRB' 'LKA' 'HTI' 'ISL' 'MAC' 'MNG' 'SYR' 'PYF' 'VCT' 'AGO'
 'COD' 'NGA' 'UGA' 'DMA' 'BLZ' 'CMR' 'CPV' 'CAF' 'COM' 'BEN' 'FJI' 'PSE'
 'GIN' 'MDG' 'MLI' 'MOZ' 'GNB' 'SEN' 'SDN' 'TON' 'MKD' 'TZA' 'BFA' 'YEM'
 'CYM' 'BMU' 'BRN' 'BES' 'AIA' 'TCA' 'SRB' 'MRT' 'MMR' 'BGD' 'ARM' 'TGO'
 'LAO' 'DJI' 'LUX' 'NCL' 'BDI' 'RWA' 'ZWE' 'MNP' 'TKM' 'MDV' 'ZMB' 'UZB'
 'LSO' 'MUS' 'TCD' 'SYC' 'MSR' 'IOT' 'TLS' 'SOM' 'SMR' 'MWI' 'ASM' 'PNG'
 'BWA' 'GMB' 'AND' 'NPL' 'NER' 'MHL' 'SWZ']

### Determinación canasta báscia de productos de importación y exportación representativos

In [135]:
# Extraer canasta representativa 60% de las importaciones
imports21_24_sintotal=imports21_24[imports21_24['cmdCode']!='TOTAL']
imports21_24_sintotal=imports21_24_sintotal[~imports21_24_sintotal['partnerISO'].isin(['S19', 'X2 ', 'W00','_X '])]
imports21_24_partida=imports21_24_sintotal[imports21_24_sintotal['cmdCode'].str.len() == 4].copy()
imports21_24_partida=imports21_24_partida[~imports21_24_partida['cmdCode'].isin(['9999'])]
imports21_24_agr=imports21_24_partida.groupby(['cmdCode','cmdDesc'])['cifvalue'].sum().reset_index()
imports21_24_agr=imports21_24_agr.sort_values(by='cifvalue', ascending=False)
total_valorcif_imp=imports21_24_agr['cifvalue'].sum()
imports21_24_agr['part_cifvalue']=imports21_24_agr['cifvalue']/total_valorcif_imp
imports21_24_agr['part_acum']=imports21_24_agr['part_cifvalue'].cumsum()
cesta_imp=imports21_24_agr[imports21_24_agr['part_acum']<=0.6]
lista_cod_cesta_imp=cesta_imp['cmdCode'].tolist()
print(lista_cod_cesta_imp)

# Extraer canasta representativa 60% de las exportaciones
exports21_24_sintotal=exports21_24[exports21_24['cmdCode']!='TOTAL']
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['partnerISO'].isin(['S19', 'X2 ', 'W00','_X '])]
exports21_24_partida=exports21_24_sintotal[exports21_24_sintotal['cmdCode'].str.len() == 4].copy()
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['cmdCode'].isin(['9999'])]
exports21_24_agr=exports21_24_partida.groupby(['cmdCode','cmdDesc'])['fobvalue'].sum().reset_index()
exports21_24_agr=exports21_24_agr.sort_values(by='fobvalue', ascending=False)
total_valorcif_exp=exports21_24_agr['fobvalue'].sum()
exports21_24_agr['part_fobvalue']=exports21_24_agr['fobvalue']/total_valorcif_imp
exports21_24_agr['part_acum']=exports21_24_agr['part_fobvalue'].cumsum()
cesta_exp=exports21_24_agr[exports21_24_agr['part_acum']<=0.6]
lista_cod_cesta_exp=cesta_exp['cmdCode'].tolist()
print(lista_cod_cesta_exp)

['2710', '8703', '3004', '8517', '1005', '3002', '8802', '8471', '2304', '8704', '3901', '1001', '8517', '4011', '8708', '9018', '8528', '3808', '7225', '7208', '2711', '2709', '3102', '2903', '3907', '3105', '8544', '2901', '1507', '8429', '0203', '8701', '3920', '2106', '9021', '7304', '8502', '7408', '3104', '8421', '8802', '8481', '8413', '2933', '8504', '0901', '1201', '2309', '3824', '8541', '5402', '8483', '8409', '8418', '3304', '8414', '7210', '8479', '7207', '3302', '8536', '8443', '2303', '2207', '8450', '6402', '2208', '3822', '4811', '4410']
['2709', '2701', '0901', '7108', '2710', '0603', '2704', '0803', '7202', '7610', '1511', '3808', '3904', '1701', '3902', '2101', '3004', '7404', '0804', '1704']

### Determinación paises socios representativos en importación y exportación

In [140]:
# Extraer canasta representativa 75% de los paises que más colombia importa
imports21_24_sintotal=imports21_24[imports21_24['cmdCode']!='TOTAL']
imports21_24_sintotal=imports21_24_sintotal[~imports21_24_sintotal['partnerISO'].isin(['S19', 'X2 ', 'W00','_X '])]
imports21_24_partida=imports21_24_sintotal[imports21_24_sintotal['cmdCode'].str.len() == 4].copy()
imports21_24_partida=imports21_24_partida[~imports21_24_partida['cmdCode'].isin(['9999'])]
imports21_24_agr=imports21_24_partida.groupby(['partnerCode','partnerISO','partnerDesc'])['cifvalue'].sum().reset_index()
imports21_24_agr=imports21_24_agr.sort_values(by='cifvalue', ascending=False)
total_valorcif_imp=imports21_24_agr['cifvalue'].sum()
imports21_24_agr['part_cifvalue']=imports21_24_agr['cifvalue']/total_valorcif_imp
imports21_24_agr['part_acum']=imports21_24_agr['part_cifvalue'].cumsum()
paises_imp=imports21_24_agr[imports21_24_agr['part_acum']<=0.75]
lista_cod_paises_imp=paises_imp['partnerCode'].tolist()
lista_cod_paises_imp_iso=paises_imp['partnerISO'].tolist()
print(lista_cod_paises_imp_iso)

# Extraer canasta representativa 60% de los paises que más colombia exporta
exports21_24_sintotal=exports21_24[exports21_24['cmdCode']!='TOTAL']
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['partnerISO'].isin(['S19', 'X2 ', 'W00','_X '])]
exports21_24_partida=exports21_24_sintotal[exports21_24_sintotal['cmdCode'].str.len() == 4].copy()
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['cmdCode'].isin(['9999'])]
exports21_24_agr=exports21_24_partida.groupby(['partnerCode','partnerISO','partnerDesc'])['fobvalue'].sum().reset_index()
exports21_24_agr=exports21_24_agr.sort_values(by='fobvalue', ascending=False)
total_valorcif_exp=exports21_24_agr['fobvalue'].sum()
exports21_24_agr['part_fobvalue']=exports21_24_agr['fobvalue']/total_valorcif_imp
exports21_24_agr['part_acum']=exports21_24_agr['part_fobvalue'].cumsum()
paises_exp=exports21_24_agr[exports21_24_agr['part_acum']<=0.6]
lista_cod_paises_exp=paises_exp['partnerCode'].tolist()
lista_cod_paises_exp_iso=paises_exp['partnerISO'].tolist()
print(lista_cod_paises_exp_iso)

['USA', 'CHN', 'BRA', 'MEX', 'DEU', 'FRA', 'JPN', 'IND', 'ARG']
['USA', 'PAN', 'CHN', 'IND', 'BRA', 'ECU', 'NLD', 'MEX', 'TUR', 'CHL', 'PER', 'ESP', 'ITA', 'KOR', 'CAN']

## Obtención de datos de exportación e importación para 10 años para paises socios representativos y canasta representativa

In [137]:
# Socios representativos
socios_comerciales=list(set(lista_cod_paises_imp + lista_cod_paises_exp + [170]))
# Años
chunks_anios = ['2014,2015,2016,2017,2018', '2019,2020,2021,2022,2023', '2024']
# Canasta representativa
lista_cestas=list(set(lista_cod_cesta_exp + lista_cod_cesta_imp))
cmd_cadena = ','.join(str(c) for c in lista_cestas)

In [118]:
exports_imports_socios=[]
# Bucle para la API para buscar la canasta en la importación y exportacion de los socios
for socio in socios_comerciales:
  for anio in chunks_anios:
        temp = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period=anio,
                                    reporterCode=str(socio), cmdCode=cmd_cadena, flowCode='M,X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
        exports_imports_socios.append(temp)
        print('datos extradiso para: ', temp['reporterISO'].unique(), anio, temp['reporterCode'].size)
        time.sleep(3)

datos extradiso para:  ['JPN'] 2014,2015,2016,2017,2018 51548
datos extradiso para:  ['JPN'] 2019,2020,2021,2022,2023 51226
datos extradiso para:  ['JPN'] 2024 10428
datos extradiso para:  ['NLD'] 2014,2015,2016,2017,2018 94012
datos extradiso para:  ['NLD'] 2019,2020,2021,2022,2023 92241
datos extradiso para:  ['NLD'] 2024 18505
datos extradiso para:  ['DEU'] 2014,2015,2016,2017,2018 87283
datos extradiso para:  ['DEU'] 2019,2020,2021,2022,2023 88715
datos extradiso para:  ['DEU'] 2024 18098
datos extradiso para:  ['CHL'] 2014,2015,2016,2017,2018 27687
datos extradiso para:  ['CHL'] 2019,2020,2021,2022,2023 28659
datos extradiso para:  ['CHL'] 2024 5741
datos extradiso para:  ['TUR'] 2014,2015,2016,2017,2018 62591
datos extradiso para:  ['TUR'] 2019,2020,2021,2022,2023 73292
datos extradiso para:  ['TUR'] 2024 15612
datos extradiso para:  ['KOR'] 2014,2015,2016,2017,2018 64608
datos extradiso para:  ['KOR'] 2019,2020,2021,2022,2023 66014
datos extradiso para:  ['KOR'] 2024 13374
datos extradiso para:  ['CHN'] 2014,2015,2016,2017,2018 81247
datos extradiso para:  ['CHN'] 2019,2020,2021,2022,2023 86556
datos extradiso para:  ['CHN'] 2024 17613
datos extradiso para:  ['ARG'] 2014,2015,2016,2017,2018 27177
datos extradiso para:  ['ARG'] 2019,2020,2021,2022,2023 20477
datos extradiso para:  ['ARG'] 2024 3804
datos extradiso para:  ['COL'] 2014,2015,2016,2017,2018 29399
datos extradiso para:  ['COL'] 2019,2020,2021,2022,2023 30199
datos extradiso para:  ['COL'] 2024 6057
datos extradiso para:  ['IND'] 2014,2015,2016,2017,2018 68963
datos extradiso para:  ['IND'] 2019,2020,2021,2022,2023 73255
datos extradiso para:  ['IND'] 2024 14734
datos extradiso para:  ['USA'] 2014,2015,2016,2017,2018 84601
datos extradiso para:  ['USA'] 2019,2020,2021,2022,2023 85833
datos extradiso para:  ['USA'] 2024 17089
datos extradiso para:  ['BRA'] 2014,2015,2016,2017,2018 47097
datos extradiso para:  ['BRA'] 2019,2020,2021,2022,2023 52909
datos extradiso para:  ['BRA'] 2024 10753
datos extradiso para:  ['PAN'] 2014,2015,2016,2017,2018 22617
datos extradiso para:  ['PAN'] 2019,2020,2021,2022,2023 17473
datos extradiso para:  ['PAN'] 2024 3120
datos extradiso para:  ['ESP'] 2014,2015,2016,2017,2018 75716
datos extradiso para:  ['ESP'] 2019,2020,2021,2022,2023 77575
datos extradiso para:  ['ESP'] 2024 15830
datos extradiso para:  ['ECU'] 2014,2015,2016,2017,2018 20686
datos extradiso para:  ['ECU'] 2019,2020,2021,2022,2023 22063
datos extradiso para:  ['ECU'] 2024 4565
datos extradiso para:  ['PER'] 2014,2015,2016,2017,2018 24860
datos extradiso para:  ['PER'] 2019,2020,2021,2022,2023 25628
datos extradiso para:  ['PER'] 2024 5271
datos extradiso para:  ['MEX'] 2014,2015,2016,2017,2018 28319
datos extradiso para:  ['MEX'] 2019,2020,2021,2022,2023 25241
datos extradiso para:  ['MEX'] 2024 4545
datos extradiso para:  ['ITA'] 2014,2015,2016,2017,2018 75015
datos extradiso para:  ['ITA'] 2019,2020,2021,2022,2023 76107
datos extradiso para:  ['ITA'] 2024 15340
datos extradiso para:  ['FRA'] 2014,2015,2016,2017,2018 87976
datos extradiso para:  ['FRA'] 2019,2020,2021,2022,2023 92256
datos extradiso para:  ['FRA'] 2024 18820
datos extradiso para:  ['CAN'] 2014,2015,2016,2017,2018 65559
datos extradiso para:  ['CAN'] 2019,2020,2021,2022,2023 66283
datos extradiso para:  ['CAN'] 2024 13244

TypeError: list indices must be integers or slices, not str

In [124]:
# Limpieza de la base para zonas sin identificar y otros productos
exports_imports_socios_red_commodities = pd.concat(exports_imports_socios, ignore_index=True)
exports_imports_socios_red_commodities=exports_imports_socios_red_commodities[exports_imports_socios_red_commodities['cmdCode']!='TOTAL']
exports_imports_socios_red_commodities=exports_imports_socios_red_commodities[~exports_imports_socios_red_commodities['partnerISO'].isin(['X1','XX','X2 ', 'W00','_X '])]
exports_imports_socios_red_commodities

/tmp/ipykernel_7760/1791988652.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  exports_imports_socios_red_commodities = pd.concat(exports_imports_socios, ignore_index=True)

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
1,C,A,20140101,2014,52,2014,392,JPN,Japan,M,Import,36,AUS,Australia,0,W00,World,H4,HS,True,0102,Bovine animals; live,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,5,u,10489.00,False,-1,N/A,NaN,False,NaN,False,NaN,False,19554890.00,NaN,19554890.00,0,True,False
3,C,A,20140101,2014,52,2014,392,JPN,Japan,M,Import,36,AUS,Australia,0,W00,World,H4,HS,True,0203,"Meat of swine; fresh, chilled or frozen",4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,678515.00,False,-1,N/A,NaN,False,678515.00,False,NaN,False,3756490.00,NaN,3756490.00,0,True,False
4,C,A,20140101,2014,52,2014,392,JPN,Japan,M,Import,40,AUT,Austria,0,W00,World,H4,HS,True,0203,"Meat of swine; fresh, chilled or frozen",4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,17556219.00,False,-1,N/A,NaN,False,17556219.00,False,NaN,False,87154734.00,NaN,87154734.00,0,True,False
5,C,A,20140101,2014,52,2014,392,JPN,Japan,M,Import,56,BEL,Belgium,0,W00,World,H4,HS,True,0203,"Meat of swine; fresh, chilled or frozen",4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,737220.00,False,-1,N/A,NaN,False,737220.00,False,NaN,False,3650369.00,NaN,3650369.00,0,True,False
6,C,A,20140101,2014,52,2014,392,JPN,Japan,M,Import,76,BRA,Brazil,0,W00,World,H4,HS,True,0203,"Meat of swine; fresh, chilled or frozen",4,False,C00,TOTAL CPC,0,0,TOTAL MOT,8,kg,2447420.00,False,-1,N/A,NaN,False,2447420.00,False,NaN,False,12286683.00,NaN,12286683.00,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511501,C,A,20240101,2024,52,2024,124,CAN,Canada,X,Export,854,BFA,Burkina Faso,0,W00,World,H6,HS,True,9999,Commodities not specified according to kind,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,NaN,130015.57,130015.57,0,False,True
2511502,C,A,20240101,2024,52,2024,124,CAN,Canada,X,Export,858,URY,Uruguay,0,W00,World,H6,HS,True,9999,Commodities not specified according to kind,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,NaN,174668.65,174668.65,0,False,True
2511503,C,A,20240101,2024,52,2024,124,CAN,Canada,X,Export,860,UZB,Uzbekistan,0,W00,World,H6,HS,True,9999,Commodities not specified according to kind,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,NaN,1699.93,1699.93,0,False,True
2511504,C,A,20240101,2024,52,2024,124,CAN,Canada,X,Export,862,VEN,Venezuela,0,W00,World,H6,HS,True,9999,Commodities not specified according to kind,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,NaN,308502.36,308502.36,0,False,True
2511505,C,A,20240101,2024,52,2024,124,CAN,Canada,X,Export,894,ZMB,Zambia,0,W00,World,H6,HS,True,9999,Commodities not specified according to kind,4,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,NaN,603688.14,603688.14,0,False,True

In [138]:
#Verificación de la canasta básica y de los socios
codigos_descargados = set(exports_imports_socios_red_commodities['cmdCode'].unique())
codigos_esperados = set(lista_cestas)
codigos_faltantes = codigos_esperados - codigos_descargados
print(codigos_faltantes)

socios_descargados = set(exports_imports_socios_red_commodities['reporterCode'].unique())
socios_esperados = set(socios_comerciales)
socios_faltantes = socios_esperados - socios_descargados
print(socios_faltantes)

{'4410'}
set()