<a href="https://colab.research.google.com/github/hubcborja/Trabajo_grado_ECIJG/blob/main/Comtrade_Free_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Codigo de API Comtrade

Recuperado de https://github.com/uncomtrade/comtradeapicall/blob/main/tests/example%20calling%20functions%20-%20notebook.ipynb

In [3]:
import sys
!{sys.executable} -m pip install --upgrade comtradeapicall

Collecting comtradeapicall
  Downloading comtradeapicall-1.3.0-py3-none-any.whl.metadata (21 kB)
Downloading comtradeapicall-1.3.0-py3-none-any.whl (20 kB)
Installing collected packages: comtradeapicall
Successfully installed comtradeapicall-1.3.0

In [114]:
import pandas as pd
import requests
import comtradeapicall
import time
import os
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format

In [5]:
import importlib.metadata
version = importlib.metadata.version("comtradeapicall")
print("comtradeapicall version:", version)

comtradeapicall version: 1.3.0

In [8]:
PrimaryKey='cde7e1ab17694a84a7554b02b5e8f489'
SecondaryKey='d46468208db74e9c8a3ec81fb5d876b2'

In [23]:
mydf = comtradeapicall.getFinalDataAvailability(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS',
                                                period='2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025', reporterCode='170')
mydf

,datasetCode,typeCode,freqCode,period,reporterCode,reporterISO,reporterDesc,classificationCode,classificationSearchCode,isOriginalClassification,isExtendedFlowCode,isExtendedPartnerCode,isExtendedPartner2Code,isExtendedCmdCode,isExtendedCustomsCode,isExtendedMotCode,totalRecords,datasetChecksum,firstReleased,lastReleased
0,20170200601072100,C,A,2006,170,COL,Colombia,H2,HS,True,True,True,False,True,False,False,144440,1467177480,2007-03-19T08:11:57.28,2011-04-16T13:09:38.7333333
1,20170200701082100,C,A,2007,170,COL,Colombia,H3,HS,True,False,True,False,True,False,False,145127,1275774234,2008-05-02T16:57:17.7166667,2011-04-16T13:54:40.7066667
2,20170200801082100,C,A,2008,170,COL,Colombia,H3,HS,True,False,True,False,True,False,False,144778,1521521383,2009-04-09T11:26:40.2833333,2011-04-16T14:41:57.73
3,20170200901082100,C,A,2009,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,147595,-583338098,2010-03-02T12:31:00.6966667,2011-04-16T15:15:26.3166667
4,20170201001082100,C,A,2010,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,149434,-1848505451,2011-03-03T14:32:08.0466667,2011-03-03T14:32:08.0466667
5,20170201101082100,C,A,2011,170,COL,Colombia,H3,HS,True,True,True,False,True,False,False,155867,377627254,2012-03-21T18:25:49.9666667,2012-03-21T18:25:49.9666667
6,20170201201092100,C,A,2012,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,156042,968658935,2013-09-07T14:23:33.2,2013-09-07T14:23:33.2
7,20170201301092100,C,A,2013,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,158505,-347970151,2014-04-04T18:31:41.8,2014-04-04T18:31:41.8
8,20170201401092100,C,A,2014,170,COL,Colombia,H4,HS,True,True,True,False,True,False,False,160368,1626408517,2015-07-23T14:29:48.01,2015-07-23T14:29:48.01
9,20170201501092100,C,A,2015,170,COL,Colombia,H4,HS,True,False,True,False,True,False,False,157146,983557154,2016-09-01T19:10:30.06,2016-09-01T19:10:30.06
10,20170201601092100,C,A,2016,170,COL,Colombia,H4,HS,True,False,True,False,True,False,False,158225,-1885371501,2017-05-05T19:09:35.3,2017-05-05T19:09:35.3
11,20170201701182100,C,A,2017,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1349644,-1377630067,2018-07-09T13:01:27.39,2018-07-09T13:01:27.39
12,20170201801182100,C,A,2018,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1367116,-1176784435,2019-04-22T08:03:27.4266667,2019-04-22T08:03:27.4266667
13,20170201901182100,C,A,2019,170,COL,Colombia,H5,HS,True,False,True,True,True,True,True,2884876,192638454,2020-06-29T16:09:46.98,2024-07-24T11:29:10.0833333
14,20170202001182100,C,A,2020,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1419256,683623520,2021-08-04T01:25:08.1066667,2026-03-26T02:44:54.24
15,20170202101182100,C,A,2021,170,COL,Colombia,H5,HS,True,False,True,True,True,False,True,1484983,824612050,2022-06-02T20:26:52.2666667,2026-03-27T06:13:18.1433333
16,20170202201202100,C,A,2022,170,COL,Colombia,H6,HS,True,False,True,True,True,True,True,3090896,1171875941,2023-10-12T00:45:16.5933333,2026-02-16T08:07:05.61
17,20170202301202100,C,A,2023,170,COL,Colombia,H6,HS,True,False,True,True,True,True,True,3072312,-580089957,2024-06-11T18:43:13.9533333,2026-02-10T08:04:35.82
18,20170202401202100,C,A,2024,170,COL,Colombia,H6,HS,True,False,True,True,True,False,True,1550473,486048189,2025-10-01T16:40:42.3733333,2026-03-27T22:03:53.2533333

In [46]:
imp21 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2021',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp22 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2022',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp23 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2023',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
imp24 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2024',
                                    reporterCode='170', cmdCode=None, flowCode='M', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

exp21 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2021',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp22 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2022',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp23 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2023',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
exp24 = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period='2024',
                                    reporterCode='170', cmdCode=None, flowCode='X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [47]:
print(imp21['partnerCode'].size)
print(imp22['partnerCode'].size)
print(imp23['partnerCode'].size)
print(imp24['partnerCode'].size)

print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)
print(exp21['partnerCode'].size)

95155
99119
97152
97103
60447
60447
60447
60447

In [48]:
imports21_24=pd.concat([imp21, imp22, imp23, imp24])
exports21_24=pd.concat([exp21, exp22, exp23, exp24])

In [58]:
exports21_24

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,flowDesc,partnerCode,partnerISO,partnerDesc,partner2Code,partner2ISO,partner2Desc,classificationCode,classificationSearchCode,isOriginalClassification,cmdCode,cmdDesc,aggrLevel,isLeaf,customsCode,customsDesc,mosCode,motCode,motDesc,qtyUnitCode,qtyUnitAbbr,qty,isQtyEstimated,altQtyUnitCode,altQtyUnitAbbr,altQty,isAltQtyEstimated,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,0,W00,World,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,160725206.52,160725206.52,0,False,True
1,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,32,ARG,Argentina,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,3015.00,3015.00,0,False,True
2,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,40,AUT,Austria,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,50.00,50.00,0,False,True
3,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,56,BEL,Belgium,0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,200.00,200.00,0,False,True
4,C,A,20210101,2021,52,2021,170,COL,Colombia,X,Export,68,BOL,Bolivia (Plurinational State of),0,W00,World,H5,HS,True,01,Animals; live,2,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,830.00,830.00,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65878,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,860,UZB,Uzbekistan,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,645909.10,645909.10,0,False,True
65879,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,862,VEN,Venezuela,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,True,0.00,False,None,1003583583.61,1003583583.61,4,False,True
65880,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,887,YEM,Yemen,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,292992.60,292992.60,0,False,True
65881,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,894,ZMB,Zambia,0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,False,0.00,False,None,184012.60,184012.60,0,False,True
65882,C,A,20240101,2024,52,2024,170,COL,Colombia,X,Export,899,_X,"Areas, nes",0,W00,World,H6,HS,True,TOTAL,All Commodities,0,False,C00,TOTAL CPC,0,0,TOTAL MOT,-1,N/A,0.00,False,-1,N/A,0.00,False,0.00,True,0.00,False,None,18793159.87,18793159.87,4,False,True

In [75]:
print(imports21_24['partnerCode'].unique().size)
print(exports21_24['partnerCode'].unique().size)

219
199

In [83]:
print(imports21_24['partnerISO'].unique())
print(exports21_24['partnerISO'].unique())

['W00' 'ARG' 'AUS' 'AUT' 'BEL' 'BOL' 'BRA' 'CAN' 'CHL' 'CRI' 'CZE' 'DNK'
 'DOM' 'ECU' 'DEU' 'HUN' 'ITA' 'KOR' 'LTU' 'MEX' 'OMN' 'NLD' 'ABW' 'NGA'
 'PAN' 'PER' 'PRT' 'QAT' 'ROU' 'RUS' 'VNM' 'ESP' 'CHE' 'THA' 'UKR' 'GBR'
 'USA' 'URY' 'VEN' '_X ' 'PRY' 'SLB' 'MMR' 'CHN' 'GHA' 'GRL' 'GTM' 'ISL'
 'IDN' 'CIV' 'JPN' 'MDV' 'MRT' 'MUS' 'S19' 'NZL' 'NOR' 'PAK' 'PHL' 'POL'
 'SEN' 'SYC' 'IND' 'SUR' 'TTO' 'TUR' 'TZA' 'FRA' 'IRL' 'ISR' 'HND' 'KEN'
 'ZAF' 'HKG' 'MAR' 'EGY' 'DZA' 'BGR' 'GEO' 'GRC' 'IRN' 'LBN' 'SGP' 'ARE'
 'TUN' 'LKA' 'LBR' 'MDG' 'NPL' 'RWA' 'SYR' 'SLV' 'FIN' 'NIC' 'ALB' 'HRV'
 'MYS' 'NAM' 'SDN' 'UZB' 'HTI' 'BEN' 'SWE' 'X2 ' 'SRB' 'SVK' 'SAU' 'SVN'
 'JOR' 'EST' 'LVA' 'BRB' 'CUB' 'GUY' 'KHM' 'MOZ' 'BHR' 'BLR' 'CYP' 'JAM'
 'MDA' 'PCN' 'BGD' 'BIH' 'GAB' 'KAZ' 'KWT' 'LUX' 'ARM' 'BLZ' 'PRK' 'MAC'
 'MLT' 'SWZ' 'TKL' 'COM' 'LAO' 'CMR' 'PYF' 'CCK' 'SLE' 'ASM' 'ATG' 'AZE'
 'BTN' 'COG' 'ERI' 'GMB' 'CUW' 'NER' 'KNA' 'AIA' 'MKD' 'CYM' 'FRO' 'IRQ'
 'LBY' 'UGA' 'GRD' 'NRU' 'GIN' 'AND' 'COK' 'PLW' 'BRN' 'ETH' 'LSO' 'CPV'
 'TJK' 'TKM' 'DMA' 'GUM' 'BWA' 'VGB' 'AFG' 'ATF' 'PSE' 'KGZ' 'VAT' 'MNG'
 'NIU' 'SHN' 'SMR' 'STP' 'BHS' 'CAF' 'GIB' 'MWI' 'MLI' 'TON' 'TUV' 'WLF'
 'MSR' 'NFK' 'FSM' 'BDI' 'AGO' 'FJI' 'BFA' 'PNG' 'MNP' 'TGO' 'WSM' 'NCL'
 'ZWE' 'TCD' 'TLS' 'TCA' 'ZMB' 'BMU' 'CXR' 'IOT' 'MHL' 'VCT' 'BES' 'SOM'
 'LCA' 'DJI' 'KIR']
['W00' 'ARG' 'AUT' 'BEL' 'BOL' 'BRA' 'CAN' 'CHL' 'CRI' 'CYP' 'CZE' 'DNK'
 'DOM' 'ECU' 'SLV' 'EST' 'FRA' 'DEU' 'GTM' 'HND' 'HKG' 'HUN' 'IDN' 'IRQ'
 'IRL' 'ISR' 'ITA' 'JPN' 'JOR' 'KOR' 'LBN' 'MYS' 'MLT' 'MEX' 'NAM' 'NLD'
 'CUW' 'ABW' 'NOR' 'PAN' 'PRY' 'PER' 'PHL' 'PRT' 'ROU' 'RUS' 'SAU' 'IND'
 'VNM' 'ZAF' 'ESP' 'SWE' 'CHE' 'THA' 'ARE' 'EGY' 'GBR' 'USA' 'URY' 'VEN'
 'CHN' 'COG' 'GNQ' 'GAB' 'GEO' 'CIV' 'LBR' 'LBY' 'QAT' 'SLE' 'TUR' 'BGR'
 'FIN' 'S19' 'OMN' 'PAK' 'POL' 'SGP' 'AUS' 'GUY' 'SUR' 'TTO' '_X ' 'SVK'
 'X2 ' 'AFG' 'ATG' 'AZE' 'BHS' 'BHR' 'BIH' 'VGB' 'BLR' 'HRV' 'ETH' 'GHA'
 'GRD' 'GUM' 'JAM' 'KAZ' 'KEN' 'PRK' 'KWT' 'KGZ' 'LVA' 'LTU' 'MDA' 'MNE'
 'MAR' 'NZL' 'NIC' 'KNA' 'LCA' 'SVN' 'TJK' 'UKR' 'CUB' 'ALB' 'DZA' 'KHM'
 'GRC' 'TUN' 'BRB' 'LKA' 'HTI' 'ISL' 'MAC' 'MNG' 'SYR' 'PYF' 'VCT' 'AGO'
 'COD' 'NGA' 'UGA' 'DMA' 'BLZ' 'CMR' 'CPV' 'CAF' 'COM' 'BEN' 'FJI' 'PSE'
 'GIN' 'MDG' 'MLI' 'MOZ' 'GNB' 'SEN' 'SDN' 'TON' 'MKD' 'TZA' 'BFA' 'YEM'
 'CYM' 'BMU' 'BRN' 'BES' 'AIA' 'TCA' 'SRB' 'MRT' 'MMR' 'BGD' 'ARM' 'TGO'
 'LAO' 'DJI' 'LUX' 'NCL' 'BDI' 'RWA' 'ZWE' 'MNP' 'TKM' 'MDV' 'ZMB' 'UZB'
 'LSO' 'MUS' 'TCD' 'SYC' 'MSR' 'IOT' 'TLS' 'SOM' 'SMR' 'MWI' 'ASM' 'PNG'
 'BWA' 'GMB' 'AND' 'NPL' 'NER' 'MHL' 'SWZ']

In [87]:
# Extraer canasta representativa 60% de las importaciones
imports21_24_sintotal=imports21_24[imports21_24['cmdCode']!='TOTAL']
imports21_24_sintotal=imports21_24_sintotal[~imports21_24_sintotal['partnerISO'].isin(['X2 ', 'W00','_X '])]
imports21_24_partida=imports21_24_sintotal[imports21_24_sintotal['cmdCode'].str.len() == 4].copy()
imports21_24_agr=imports21_24_partida.groupby(['cmdCode','cmdDesc'])['cifvalue'].sum().reset_index()
imports21_24_agr=imports21_24_agr.sort_values(by='cifvalue', ascending=False)
total_valorcif_imp=imports21_24_agr['cifvalue'].sum()
imports21_24_agr['part_cifvalue']=imports21_24_agr['cifvalue']/total_valorcif_imp
imports21_24_agr['part_acum']=imports21_24_agr['part_cifvalue'].cumsum()
cesta_imp=imports21_24_agr[imports21_24_agr['part_acum']<=0.6]
lista_cod_cesta_imp=cesta_imp['cmdCode'].tolist()
print(lista_cod_cesta_imp)

# Extraer canasta representativa 60% de las exportaciones
exports21_24_sintotal=exports21_24[exports21_24['cmdCode']!='TOTAL']
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['partnerISO'].isin(['X2 ', 'W00','_X '])]
exports21_24_partida=exports21_24_sintotal[exports21_24_sintotal['cmdCode'].str.len() == 4].copy()
exports21_24_agr=exports21_24_partida.groupby(['cmdCode','cmdDesc'])['fobvalue'].sum().reset_index()
exports21_24_agr=exports21_24_agr.sort_values(by='fobvalue', ascending=False)
total_valorcif_exp=exports21_24_agr['fobvalue'].sum()
exports21_24_agr['part_fobvalue']=exports21_24_agr['fobvalue']/total_valorcif_imp
exports21_24_agr['part_acum']=exports21_24_agr['part_fobvalue'].cumsum()
cesta_exp=exports21_24_agr[exports21_24_agr['part_acum']<=0.6]
lista_cod_cesta_exp=cesta_exp['cmdCode'].tolist()
print(lista_cod_cesta_exp)

['2710', '8703', '3004', '8517', '1005', '3002', '8471', '8802', '2304', '8704', '3901', '1001', '8517', '4011', '8708', '9018', '8528', '9999', '3808', '7225', '7208', '2711', '2709', '3102', '3907', '2903', '3105', '2901', '8544', '1507', '8429', '0203', '3920', '8701', '2106', '9021', '7304', '8502', '7408', '3104', '8421', '8802', '8481', '8413', '2933', '8504', '0901', '1201', '2309', '3824', '8541', '5402', '8483', '8414', '8409', '8418', '3304', '7210', '8479', '7207', '8536', '3302', '8443', '2303', '2207', '8450', '6402', '8714', '2208', '3822', '4811']
['2709', '2701', '0901', '7108', '2710', '0603', '2704', '0803', '7202', '7610', '1511', '3808', '3904', '1701', '3902', '2101', '3004', '7404', '0804', '1704', '0102', '3304']

In [82]:
imports21_24['partnerDesc'].unique()

array(['World', 'Argentina', 'Australia', 'Austria', 'Belgium',
       'Bolivia (Plurinational State of)', 'Brazil', 'Canada', 'Chile',
       'Costa Rica', 'Czechia', 'Denmark', 'Dominican Rep.', 'Ecuador',
       'Germany', 'Hungary', 'Italy', 'Rep. of Korea', 'Lithuania',
       'Mexico', 'Oman', 'Netherlands', 'Aruba', 'Nigeria', 'Panama',
       'Peru', 'Portugal', 'Qatar', 'Romania', 'Russian Federation',
       'Viet Nam', 'Spain', 'Switzerland', 'Thailand', 'Ukraine',
       'United Kingdom', 'USA', 'Uruguay', 'Venezuela', 'Areas, nes',
       'Paraguay', 'Solomon Isds', 'Myanmar', 'China', 'Ghana',
       'Greenland', 'Guatemala', 'Iceland', 'Indonesia', "Côte d'Ivoire",
       'Japan', 'Maldives', 'Mauritania', 'Mauritius', 'Other Asia, nes',
       'New Zealand', 'Norway', 'Pakistan', 'Philippines', 'Poland',
       'Senegal', 'Seychelles', 'India', 'Suriname',
       'Trinidad and Tobago', 'Türkiye', 'United Rep. of Tanzania',
       'France', 'Ireland', 'Israel', 'Honduras', 'Kenya', 'South Africa',
       'China, Hong Kong SAR', 'Morocco', 'Egypt', 'Algeria', 'Bulgaria',
       'Georgia', 'Greece', 'Iran', 'Lebanon', 'Singapore',
       'United Arab Emirates', 'Tunisia', 'Sri Lanka', 'Liberia',
       'Madagascar', 'Nepal', 'Rwanda', 'Syria', 'El Salvador', 'Finland',
       'Nicaragua', 'Albania', 'Croatia', 'Malaysia', 'Namibia', 'Sudan',
       'Uzbekistan', 'Haiti', 'Benin', 'Sweden', 'Free Zones', 'Serbia',
       'Slovakia', 'Saudi Arabia', 'Slovenia', 'Jordan', 'Estonia',
       'Latvia', 'Barbados', 'Cuba', 'Guyana', 'Cambodia', 'Mozambique',
       'Bahrain', 'Belarus', 'Cyprus', 'Jamaica', 'Rep. of Moldova',
       'Pitcairn', 'Bangladesh', 'Bosnia Herzegovina', 'Gabon',
       'Kazakhstan', 'Kuwait', 'Luxembourg', 'Armenia', 'Belize',
       "Dem. People's Rep. of Korea", 'China, Macao SAR', 'Malta',
       'Eswatini', 'Tokelau', 'Comoros', "Lao People's Dem. Rep.",
       'Cameroon', 'French Polynesia', 'Cocos Isds', 'Sierra Leone',
       'American Samoa', 'Antigua and Barbuda', 'Azerbaijan', 'Bhutan',
       'Congo', 'Eritrea', 'Gambia', 'Curaçao', 'Niger',
       'Saint Kitts and Nevis', 'Anguilla', 'North Macedonia',
       'Cayman Isds', 'Faroe Isds', 'Iraq', 'Libya', 'Uganda', 'Grenada',
       'Nauru', 'Guinea', 'Andorra', 'Cook Isds', 'Palau',
       'Brunei Darussalam', 'Ethiopia', 'Lesotho', 'Cabo Verde',
       'Tajikistan', 'Turkmenistan', 'Dominica', 'Guam', 'Botswana',
       'Br. Virgin Isds', 'Afghanistan', 'Fr. South Antarctic Terr.',
       'State of Palestine', 'Kyrgyzstan',
       'Holy See (Vatican City State)', 'Mongolia', 'Niue',
       'Saint Helena', 'San Marino', 'Sao Tome and Principe', 'Bahamas',
       'Central African Rep.', 'Gibraltar', 'Malawi', 'Mali', 'Tonga',
       'Tuvalu', 'Wallis and Futuna Isds', 'Montserrat', 'Norfolk Isds',
       'FS Micronesia', 'Burundi', 'Angola', 'Fiji', 'Burkina Faso',
       'Papua New Guinea', 'N. Mariana Isds', 'Togo', 'Samoa',
       'New Caledonia', 'Zimbabwe', 'Chad', 'Timor-Leste',
       'Turks and Caicos Isds', 'Zambia', 'Bermuda', 'Christmas Isds',
       'Br. Indian Ocean Terr.', 'Marshall Isds',
       'Saint Vincent and the Grenadines', 'Bonaire', 'Somalia',
       'Saint Lucia', 'Djibouti', 'Kiribati'], dtype=object)

In [105]:
# Extraer canasta representativa 60% de los paises que más colombia importa
imports21_24_sintotal=imports21_24[imports21_24['cmdCode']!='TOTAL']
imports21_24_sintotal=imports21_24_sintotal[~imports21_24_sintotal['partnerISO'].isin(['X2 ', 'W00','_X '])]
imports21_24_partida=imports21_24_sintotal[imports21_24_sintotal['cmdCode'].str.len() == 4].copy()
imports21_24_agr=imports21_24_partida.groupby(['partnerCode','partnerISO','partnerDesc'])['cifvalue'].sum().reset_index()
imports21_24_agr=imports21_24_agr.sort_values(by='cifvalue', ascending=False)
total_valorcif_imp=imports21_24_agr['cifvalue'].sum()
imports21_24_agr['part_cifvalue']=imports21_24_agr['cifvalue']/total_valorcif_imp
imports21_24_agr['part_acum']=imports21_24_agr['part_cifvalue'].cumsum()
paises_imp=imports21_24_agr[imports21_24_agr['part_acum']<=0.75]
lista_cod_paises_imp=paises_imp['partnerCode'].tolist()
print(lista_cod_paises_imp)

# Extraer canasta representativa 60% de los paises que más colombia exporta
exports21_24_sintotal=exports21_24[exports21_24['cmdCode']!='TOTAL']
exports21_24_sintotal=exports21_24_sintotal[~exports21_24_sintotal['partnerISO'].isin(['X2 ', 'W00','_X '])]
exports21_24_partida=exports21_24_sintotal[exports21_24_sintotal['cmdCode'].str.len() == 4].copy()
exports21_24_agr=exports21_24_partida.groupby(['partnerCode','partnerISO','partnerDesc'])['fobvalue'].sum().reset_index()
exports21_24_agr=exports21_24_agr.sort_values(by='fobvalue', ascending=False)
total_valorcif_exp=exports21_24_agr['fobvalue'].sum()
exports21_24_agr['part_fobvalue']=exports21_24_agr['fobvalue']/total_valorcif_imp
exports21_24_agr['part_acum']=exports21_24_agr['part_fobvalue'].cumsum()
paises_exp=exports21_24_agr[exports21_24_agr['part_acum']<=0.6]
lista_cod_paises_exp=paises_exp['partnerCode'].tolist()
print(lista_cod_paises_exp)

[842, 156, 76, 484, 276, 251, 699, 392, 32]
[842, 591, 156, 699, 76, 218, 528, 484, 792, 152, 604, 724, 380, 410, 124, 276]

In [116]:
socios_comerciales=list(set(lista_cod_paises_imp + lista_cod_paises_exp + [170]))
chunks_anios = ['2014,2015,2016,2017,2018', '2019,2020,2021,2022,2023', '2024']
modalidad=['M', 'X']
lista_cestas=list(set(lista_cod_cesta_exp + lista_cod_cesta_imp))
cmd_cadena = ','.join(str(c) for c in lista_cestas)

In [ ]:
exports_imports_socios=[]
for socio in socios_comerciales:
  for anio in chunks_anios:
        temp = comtradeapicall.getFinalData(subscription_key=PrimaryKey, typeCode='C', freqCode='A', clCode='HS', period=anio,
                                    reporterCode=str(socio), cmdCode=cmd_cadena, flowCode='M,X', partnerCode=None,partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=100000, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)
        exports_imports_socios.append(temp)
        print('datos extradiso para: ', temp['reporterISO'].unique(), anio, temp['reporterCode'].size)
        time.sleep(3)


for cod_paises in exports_imports_socios['partnerCode'].unique():
   print(cod_paises)
for iso3_paises in exports_imports_socios['partnerISO'].unique():
  print(iso3_paises)
for cod_commodity in exports_imports_socios['cmdCode'].unique():
  print(cod_commodity)
for des_commodity in exports_imports_socios['cmdDesc'].unique():
  print(des_commodity)

In [99]:
paises_exp

    partnerISO    partnerDesc       fobvalue  part_fobvalue  part_acum
186        USA            USA 56105347763.94           0.22       0.22
140        PAN         Panama 17188423380.31           0.07       0.28
36         CHN          China 10661219864.24           0.04       0.32
82         IND          India  9608695752.80           0.04       0.36
28         BRA         Brazil  8194497744.71           0.03       0.39
55         ECU        Ecuador  7576171628.45           0.03       0.42
134        NLD    Netherlands  7265304383.94           0.03       0.45
114        MEX         Mexico  6790177670.05           0.03       0.47
181        TUR        Türkiye  5184802567.03           0.02       0.49
35         CHL          Chile  4738697111.90           0.02       0.51
141        PER           Peru  4494299207.87           0.02       0.53
57         ESP          Spain  4069477873.98           0.02       0.55
88         ITA          Italy  3486259842.10           0.01       0.56
97         KOR  Rep. of Korea  3200320812.08           0.01       0.57
33         CAN         Canada  3167910619.25           0.01       0.58
49         DEU        Germany  2779650583.98           0.01       0.59

In [32]:
for cod_paises in mydf['partnerCode'].unique():
   print(cod_paises)
for iso3_paises in mydf['partnerISO'].unique():
  print(iso3_paises)
for cod_commodity in mydf['cmdCode'].unique():
  print(cod_commodity)
for des_commodity in mydf['cmdDesc'].unique():
  print(des_commodity)

0
32
36
56
76
124
152
178
188
214
218
276
300
320
328
348
410
470
484
490
498
528
531
591
604
608
620
642
643
682
710
724
752
757
764
780
792
804
826
842
862
899
208
251
380
600
858
104
156
258
296
352
360
384
392
554
579
616
686
699
704
740
834
68
203
372
838
40
340
376
404
818
344
364
504
12
51
100
144
268
422
784
788
430
450
458
702
760
440
8
204
558
566
586
860
222
716
729
288
478
480
512
428
246
688
703
116
400
233
192
388
191
52
196
508
31
612
748
795
166
408
414
634
705
442
446
520
540
50
706
96
674
772
44
84
332
70
4
20
48
64
72
112
533
562
570
807
466
524
694
136
646
516
148
231
16
316
324
418
426
496
140
232
659
598
368
768
120
308
212
398
162
580
894
24
28
275
292
336
417
660
690
762
92
184
270
678
662
60
262
654
242
W00
ARG
AUS
BEL
BRA
CAN
CHL
COG
CRI
DOM
ECU
DEU
GRC
GTM
GUY
HUN
KOR
MLT
MEX
S19
MDA
NLD
CUW
PAN
PER
PHL
PRT
ROU
RUS
SAU
ZAF
ESP
SWE
CHE
THA
TTO
TUR
UKR
GBR
USA
VEN
_X
DNK
FRA
ITA
PRY
URY
MMR
CHN
PYF
KIR
ISL
IDN
CIV
JPN
NZL
NOR
POL
SEN
IND
VNM
SUR
TZA
BOL
CZE
IRL
X2
AUT
HND
ISR
KEN
EGY
HKG
IRN
MAR
DZA
ARM
BGR
LKA
GEO
LBN
ARE
TUN
LBR
MDG
MYS
SGP
SYR
LTU
ALB
BEN
NIC
NGA
PAK
UZB
SLV
ZWE
SDN
GHA
MRT
MUS
OMN
LVA
FIN
SRB
SVK
KHM
JOR
EST
CUB
JAM
HRV
BRB
CYP
MOZ
AZE
PCN
SWZ
TKM
CCK
PRK
KWT
QAT
SVN
LUX
MAC
NRU
NCL
BGD
SOM
BRN
SMR
TKL
BHS
BLZ
HTI
BIH
AFG
AND
BHR
BTN
BWA
BLR
ABW
NER
NIU
MKD
MLI
NPL
SLE
CYM
RWA
NAM
TCD
ETH
ASM
GUM
GIN
LAO
LSO
MNG
CAF
ERI
KNA
PNG
IRQ
TGO
CMR
GRD
DMA
KAZ
CXR
MNP
ZMB
AGO
ATG
PSE
GIB
VAT
KGZ
AIA
SYC
TJK
VGB
COK
GMB
STP
LCA
BMU
DJI
SHN
FJI
01
0101
010121
010129
010130
0103
010310
010392
0105
010511
0106
010613
010619
010690
02
0201
020120
020130
0202
020220
020230
0203
020319
020321
020322
020329
0204
020442
020443
0206
020610
020621
020622
020629
020649
0207
020712
020714
020725
020727
020742
020744
020745
0208
020890
0209
020910
020990
0210
021011
021012
021019
03
0302
030213
030214
030219
030229
030235
030249
030271
030272
030279
030284
030289
030291
0303
030312
030313
030314
030323
030324
030325
030326
030329
030342
030343
030344
030354
030355
030357
030359
030366
030367
030369
030381
030384
030389
030391
030399
0304
030431
030432
030441
030442
030445
030452
030459
030461
030462
030463
030471
030474
030475
030481
030482
030487
030489
030491
030493
030494
030495
030499
0305
030541
030543
030544
030559
030572
0306
030614
030616
030617
030632
030635
030636
0307
030712
030729
030732
030743
030749
030752
030759
030772
030779
030792
0309
030910
030990
04
0401
040110
040150
0402
040210
040221
040229
040299
0403
040320
040390
0404
040410
040490
0405
040510
040590
0406
040610
040620
040630
040640
040690
0407
040711
040719
040721
0408
040811
040891
0409
040900
0410
041090
05
0502
050210
0504
050400
0505
050510
050590
0508
050800
0510
051000
0511
051110
051191
051199
06
0601
060110
060120
0602
060210
060220
060240
060290
0603
060311
060312
060314
060315
060319
060390
0604
060420
060490
07
0703
070310
070320
0706
070610
0708
070820
0709
070920
070956
070991
070999
0710
071021
071022
071029
071030
071040
071080
071090
0711
071120
071140
071159
071190
0712
071220
071231
071233
071234
071239
071290
0713
071310
071320
071331
071332
071333
071335
071339
071340
071390
0714
071420
071440
08
0801
080111
080112
080119
080122
080132
0802
080212
080222
080231
080232
080251
080252
080262
080292
080299
0803
080310
080390
0804
080410
080420
080430
080440
080450
0805
080510
080521
080522
080529
080540
080550
080590
0806
080610
080620
0808
080810
080830
0809
080929
080930
080940
0810
081040
081050
081060
081090
0811
081110
081120
081190
0812
081210
0813
081310
081320
081330
081340
081350
09
0901
090111
090112
090121
090122
0902
090210
090220
090230
090240
0903
090300
0904
090411
090412
090421
090422
0905
090520
0906
090611
090619
090620
0907
090710
090720
0908
090811
090812
090831
0909
090921
090922
090931
090932
090961
090962
0910
091011
091012
091020
091030
091091
091099
10
1001
100119
100199
1002
100290
1003
100310
100390
1004
100410
100490
1005
100510
100590
1006
100610
100620
100630
100640
1007
100710
100790
1008
100829
100830
100850
100890
11
1101
110100
1102
110220
110290
1103
110311
110313
1104
110412
110419
110422
110429
110430
1105
110520
1106
110610
110620
110630
1107
110710
110720
1108
110811
110812
110813
110814
110819
110820
1109
110900
12
1201
120110
120190
1202
120241
120242
1204
120400
1205
120510
120590
1206
120600
1207
120710
120721
120740
120750
120760
120770
120791
120799
1208
120810
120890
1209
120910
120921
120922
120923
120925
120929
120930
120991
120999
1210
121020
1211
121120
121190
1212
121221
121229
121291
121299
1214
121410
121490
13
1301
130120
130190
1302
130212
130213
130219
130220
130231
130232
130239
14
1401
140110
140120
140190
1404
140490
15
1501
150190
1503
150300
1504
150410
150420
1505
150500
1506
150600
1507
150710
150790
1508
150890
1509
150920
150930
150940
150990
1510
151010
151090
1511
151110
151190
1512
151211
151219
151221
151229
1513
151311
151319
151321
151329
1514
151411
151419
151499
1515
151511
151519
151529
151530
151550
151560
151590
1516
151610
151620
1517
151710
151790
1518
151800
1520
152000
1521
152110
152190
16
1601
160100
1602
160220
160231
160232
160239
160241
160242
160249
160250
1603
160300
1604
160412
160413
160414
160415
160416
160419
160420
160431
160432
1605
160510
160529
160540
160552
160553
160554
160555
160556
160558
160559
160569
17
1701
170113
170114
170191
170199
1702
170211
170219
170220
170230
170240
170250
170260
170290
1703
170310
170390
1704
170410
170490
18
1801
180100
1802
180200
1803
180310
1804
180400
1805
180500
1806
180610
180620
180631
180632
180690
19
1901
190110
190120
190190
1902
190211
190219
190220
190230
190240
1903
190300
1904
190410
190420
190430
190490
1905
190510
190520
190531
190532
190540
190590
20
2001
200110
200190
2002
200210
200290
2003
200310
200390
2004
200410
200490
2005
200510
200520
200540
200551
200559
200560
200570
200580
200591
200599
2006
200600
2007
200710
200791
200799
2008
200811
200819
200820
200830
200840
200850
200860
200870
200880
200893
200897
200899
2009
200911
200912
200919
200929
200931
200939
200949
200950
200961
200969
200971
200979
200981
200989
200990
21
2101
210111
210112
210120
210130
2102
210210
210220
210230
2103
210310
210320
210330
210390
2104
210410
210420
2105
210500
2106
210610
210690
22
2201
220110
220190
2202
220210
220291
220299
2203
220300
2204
220410
220421
220422
220429
220430
2205
220510
2206
220600
2207
220710
220720
2208
220820
220830
220840
220850
220860
220870
220890
2209
220900
23
2301
230110
230120
2302
230210
230230
230240
2303
230310
230320
230330
2304
230400
2306
230610
230630
230641
230650
230660
230690
2308
230800
2309
230910
230990
24
2401
240110
240120
240130
2402
240210
240220
2403
240311
240319
2404
240411
240412
240419
240491
240492
240499
25
2501
250100
2502
250200
2503
250300
2504
250410
250490
2505
250510
250590
2506
250610
2507
250700
2508
250810
250830
250840
250850
250860
250870
2509
250900
2510
251020
2511
251110
251120
2512
251200
2513
251310
251320
2514
251400
2515
251511
251512
2516
251611
251612
251620
251690
2517
251710
251749
2518
251820
2519
251910
251990
2520
252010
252020
2521
252100
2522
252210
252220
2523
252310
252321
252329
252330
252390
2525
252510
252520
2526
252610
252620
2528
252800
2529
252910
252921
252922
252930
2530
253010
253020
253090
26
2601
260111
260120
2602
260200
2604
260400
2606
260600
2610
261000
2611
261100
2613
261390
2614
261400
2615
261510
2616
261690
2617
261790
2618
261800
2619
261900
2620
262011
262019
262030
262099
2621
262190
27
2701
270111
270112
270119
2702
270210
2703
270300
2704
270400
2705
270500
2706
270600
2707
270730
270750
270791
270799
2708
270810
2709
270900
2710
271012
271019
271020
2711
271111
271112
271113
271114
271119
271121
271129
2712
271210
271220
271290
2713
271311
271312
271320
2714
271490
2715
271500
2716
271600
28
2801
280110
280120
280130
2802
280200
2803
280300
2804
280410
280421
280429
280430
280440
280450
280469
280470
280480
280490
2805
280511
280512
280519
2806
280610
2807
280700
2808
280800
2809
280910
280920
2810
281000
2811
281111
281112
281119
281121
281122
281129
2812
281213
281217
281219
281290
2813
281310
281390
2814
281410
281420
2815
281511
281512
281520
281530
2816
281610
281640
2817
281700
2818
281810
281820
281830
2819
281910
281990
2820
282010
282090
2821
282110
282120
2822
282200
2823
282300
2824
282410
282490
2825
282510
282520
282530
282540
282550
282560
282570
282580
282590
2826
282619
282630
282690
2827
282710
282720
282731
282732
282735
282739
282741
282749
282751
282759
282760
2828
282810
282890
2829
282911
282919
282990
2830
283010
283090
2831
283110
283190
2832
283210
283220
283230
2833
283311
283319
283321
283322
283324
283325
283327
283329
283330
283340
2834
283410
283421
283429
2835
283510
283522
283524
283525
283526
283529
283531
283539
2836
283620
283630
283640
283650
283660
283691
283692
283699
2837
283711
283719
283720
2839
283911
283919
283990
2840
284011
284019
284020
284030
2841
284130
284150
284161
284169
284170
284180
284190
2842
284210
284290
2843
284310
284321
284329
284330
284390
2844
284410
284420
284442
284443
2845
284510
284590
2846
284610
284690
2847
284700
2849
284910
284920
284990
2850
285000
2852
285210
285290
2853
285390
29
2901
290110
290121
290122
290123
290129
2902
290211
290219
290220
290230
290241
290242
290243
290244
290250
290260
290290
2903
290312
290313
290315
290319
290321
290322
290323
290329
290342
290343
290344
290345
290346
290347
290349
290351
290359
290369
290371
290379
290381
290382
290389
290391
290399
2904
290410
290420
290499
2905
290511
290512
290513
290514
290516
290517
290519
290522
290529
290531
290532
290539
290541
290542
290543
290544
290545
290549
290559
2906
290611
290612
290613
290619
290621
290629
2907
290711
290712
290713
290715
290719
290721
290722
290723
290729
2908
290819
290892
290899
2909
290911
290919
290920
290930
290941
290943
290944
290949
290950
290960
2910
291010
291020
291030
291040
291090
2911
291100
2912
291211
291212
291219
291221
291229
291241
291242
291249
291250
291260
2913
291300
2914
291411
291412
291413
291419
291422
291423
291429
291439
291440
291450
291461
291462
291469
291479
2915
291511
291512
291513
291521
291524
291529
291531
291532
291533
291539
291540
291550
291560
291570
291590
2916
291611
291612
291613
291614
291615
291619
291620
291631
291632
291634
291639
2917
291711
291712
291713
291714
291719
291720
291732
291733
291734
291735
291736
291737
291739
2918
291811
291812
291813
291814
291815
291816
291819
291821
291822
291823
291829
291830
291891
291899
2919
291990
2920
292011
292019
292024
292029
292030
292090
2921
292111
292112
292119
292121
292122
292129
292130
292141
292142
292143
292144
292145
292146
292149
292151
292159
2922
292211
292212
292215
292217
292219
292221
292229
292231
292239
292241
292242
292249
292250
2923
292310
292320
292390
2924
292412
292419
292421
292429
2925
292511
292519
292529
2926
292610
292620
292690
2927
292700
2928
292800
2929
292910
292990
2930
293020
293030
293040
293080
293090
2931
293120
293144
293148
293149
293154
293159
293190
2932
293211
293212
293213
293214
293219
293220
293293
293295
293296
293299
2933
293311
293319
293321
293329
293331
293332
293333
293339
293349
293352
293353
293354
293355
293359
293361
293369
293371
293372
293379
293391
293399
2934
293410
293420
293430
293491
293499
2935
293590
2936
293621
293622
293623
293624
293625
293626
293627
293628
293629
293690
2937
293712
293719
293721
293722
293723
293729
293750
293790
2938
293810
293890
2939
293911
293919
293920
293930
293941
293942
293949
293959
293962
293969
293972
293979
293980
2940
294000
2941
294110
294120
294130
294140
294150
294190
2942
294200
30
3001
300120
300190
3002
300212
300213
300214
300215
300241
300242
300249
300251
300259
300290
3003
300310
300320
300339
300342
300349
300360
300390
3004
300410
300420
300431
300432
300439
300441
300449
300450
300460
300490
3005
300510
300590
3006
300610
300630
300640
300650
300660
300670
300691
300693
31
3101
310100
3102
310210
310221
310229
310230
310250
310260
310280
310290
3103
310311
310319
310390
3104
310420
310430
310490
3105
310510
310520
310530
310540
310551
310559
310560
310590
32
3201
320110
320120
320190
3202
320210
320290
3203
320300
3204
320411
320412
320413
320414
320415
320416
320417
320418
320419
320420
320490
3205
320500
3206
320611
320619
320620
320641
320642
320649
320650
3207
320710
320720
320730
320740
3208
320810
320820
320890
3209
320910
320990
3210
321000
3211
321100
3212
321210
321290
3213
321310
321390
3214
321410
321490
3215
321511
321519
321590
33
3301
330112
330113
330119
330124
330125
330129
330130
330190
3302
330210
330290
3303
330300
3304
330410
330420
330430
330491
330499
3305
330510
330520
330530
330590
3306
330610
330620
330690
3307
330710
330720
330730
330741
330749
330790
34
3401
340111
340119
340120
340130
3402
340231
340239
340241
340242
340249
340250
340290
3403
340311
340319
340391
340399
3404
340420
340490
3405
340510
340520
340530
340540
340590
3406
340600
3407
340700
35
3501
350110
350190
3502
350211
350220
350290
3503
350300
3504
350400
3505
350510
350520
3506
350610
350691
350699
3507
350710
350790
36
3601
360100
3602
360200
3603
360320
360330
360340
360350
360360
3604
360410
360490
3605
360500
3606
360610
360690
37
3701
370110
370120
370130
370191
370199
3702
370210
370231
370239
370243
370244
370252
370256
370298
3703
370310
370320
370390
3704
370400
3705
370500
3706
370610
3707
370710
370790
38
3801
380110
380120
380130
380190
3802
380210
380290
3803
380300
3804
380400
3805
380510
380590
3806
380610
380620
380630
380690
3807
380700
3808
380859
380861
380862
380869
380891
380892
380893
380894
380899
3809
380910
380991
380992
380993
3810
381010
381090
3811
381111
381119
381121
381129
381190
3812
381210
381220
381231
381239
3813
381300
3814
381400
3815
381511
381512
381519
381590
3816
381600
3817
381700
3818
381800
3819
381900
3820
382000
3821
382100
3822
382211
382212
382213
382219
382290
3823
382311
382312
382313
382319
382370
3824
382410
382430
382440
382450
382460
382481
382482
382489
382491
382492
382499
3826
382600
3827
382731
382751
382761
382762
382763
382764
382765
382768
382769
382790
39
3901
390110
390120
390130
390140
390190
3902
390210
390220
390230
390290
3903
390311
390319
390320
390330
390390
3904
390410
390421
390422
390430
390440
390461
390469
390490
3905
390512
390519
390521
390529
390530
390591
390599
3906
390610
390690
3907
390710
390721
390729
390730
390740
390750
390761
390769
390770
390791
390799
3908
390810
390890
3909
390910
390920
390931
390939
390940
390950
3910
391000
3911
391110
391120
391190
3912
391211
391212
391220
391231
391239
391290
3913
391310
391390
3914
391400
3915
391510
391520
391530
391590
3916
391610
391620
391690
3917
391710
391721
391722
391723
391729
391731
391732
391733
391739
391740
3918
391810
391890
3919
391910
391990
3920
392010
392020
392030
392043
392049
392051
392059
392061
392062
392063
392069
392071
392073
392079
392091
392092
392093
392094
392099
3921
392111
392112
392113
392114
392119
392190
3922
392210
392220
392290
3923
392310
392321
392329
392330
392340
392350
392390
3924
392410
392490
3925
392510
392520
392530
392590
3926
392610
392620
392630
392640
392690
40
4001
400110
400121
400122
400129
400130
4002
400211
400219
400220
400231
400239
400241
400249
400251
400259
400260
400270
400291
400299
4003
400300
4004
400400
4005
400510
400520
400591
400599
4006
400610
400690
4007
400700
4008
400811
400819
400821
400829
4009
400911
400912
400921
400922
400931
400932
400941
400942
4010
401011
401012
401019
401031
401032
401033
401034
401035
401036
401039
4011
401110
401120
401130
401140
401150
401170
401180
401190
4012
401213
401220
401290
4013
401310
401320
401390
4014
401410
401490
4015
401512
401519
401590
4016
401610
401691
401692
401693
401694
401695
401699
4017
401700
41
4101
410120
410150
4104
410411
410419
410441
410449
4107
410711
410712
410719
410791
410792
410799
4112
411200
4113
411310
411320
411330
4114
411410
411420
4115
411510
411520
42
4201
420100
4202
420211
420212
420219
420221
420222
420229
420231
420232
420239
420291
420292
420299
4203
420310
420321
420329
420330
420340
4205
420500
4206
420600
43
4302
430219
430230
4303
430310
430390
4304
430400
44
4401
440112
440121
440122
440131
440139
440141
440149
4402
440210
440220
440290
4403
440311
440349
4404
440410
440420
4405
440500
4406
440691
440692
4407
440711
440712
440719
440722
440723
440729
440791
440792
440793
440794
440797
440799
4408
440810
440839
440890
4409
440910
440921
440922
440929
4410
441011
441012
441019
441090
4411
441112
441113
441114
441192
441193
441194
4412
441210
441231
441233
441234
441239
441241
441242
441249
441251
441252
441259
441291
441292
441299
4413
441300
4414
441410
441490
4415
441510
441520
4416
441600
4417
441700
4418
441811
441819
441821
441829
441830
441840
441850
441873
441874
441875
441879
441881
441882
441883
441889
441891
441892
441899
4419
441911
441912
441919
441920
441990
4420
442011
442019
442090
4421
442110
442191
442199
45
4501
450110
450190
4503
450310
450390
4504
450410
450490
46
4601
460121
460122
460129
460192
460193
460194
460199
4602
460211
460212
460219
460290
47
4701
470100
4702
470200
4703
470311
470321
470329
4704
470429
4705
470500
4706
470610
470620
470630
470691
470692
470693
4707
470710
470720
470730
470790
48
4801
480100
4802
480210
480220
480240
480254
480255
480256
480257
480258
480261
480262
480269
4803
480300
4804
480411
480419
480421
480429
480431
480439
480441
480442
480449
480451
480452
480459
4805
480511
480519
480524
480525
480530
480540
480591
480592
480593
4806
480610
480620
480630
480640
4807
480700
4808
480810
480840
480890
4809
480920
480990
4810
481013
481014
481019
481022
481029
481031
481032
481039
481092
481099
4811
481110
481141
481149
481151
481159
481160
481190
4812
481200
4813
481310
481320
481390
4814
481420
481490
4816
481620
481690
4817
481710
481720
481730
4818
481810
481820
481830
481850
481890
4819
481910
481920
481930
481940
481950
481960
4820
482010
482020
482030
482040
482050
482090
4821
482110
482190
4822
482210
482290
4823
482320
482340
482361
482369
482370
482390
49
4901
490110
490191
490199
4902
490290
4903
490300
4904
490400
4905
490520
490590
4906
490600
4907
490700
4908
490810
490890
4909
490900
4910
491000
4911
491110
491191
491199
50
5004
500400
5006
500600
5007
500720
500790
51
5102
510219
5105
510529
510539
510540
5107
510710
5108
510820
5109
510910
510990
5111
511111
511119
511130
511190
5112
511211
511219
511220
511230
511290
5113
511300
52
5201
520100
5202
520210
520299
5203
520300
5204
520411
520419
520420
5205
520511
520512
520513
520514
520522
520523
520524
520526
520527
520528
520531
520532
520535
520542
520543
520544
520547
5206
520611
520612
520622
520623
520631
520632
520641
520642
520643
520644
5207
520710
520790
5208
520811
520812
520813
520819
520821
520822
520823
520829
520831
520832
520833
520839
520841
520842
520843
520849
520851
520852
520859
5209
520911
520912
520919
520921
520922
520929
520931
520932
520939
520941
520942
520943
520949
520951
520952
520959
5210
521011
521019
521021
521029
521031
521032
521039
521041
521049
521051
521059
5211
521111
521112
521119
521120
521131
521132
521139
521141
521142
521143
521149
521151
521152
521159
5212
521211
521212
521213
521214
521215
521221
521222
521223
521224
521225
53
5302
530290
5303
530310
530390
5305
530500
5306
530610
5307
530710
530720
5308
530820
530890
5309
530911
530919
530921
530929
5310
531010
531090
5311
531100
54
5401
540110
540120
5402
540211
540219
540220
540231
540232
540233
540234
540239
540244
540245
540246
540247
540248
540249
540251
540252
540253
540259
540261
540262
540263
540269
5403
540331
540339
540341
540349
5404
540411
540412
540419
540490
5405
540500
5406
540600
5407
540710
540720
540730
540741
540742
540743
540744
540751
540752
540753
540754
540761
540769
540771
540772
540773
540774
540781
540782
540783
540784
540791
540792
540793
540794
5408
540810
540821
540822
540823
540824
540831
540832
540833
540834
55
5501
550111
550119
550130
550140
550190
5502
550210
5503